# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ea2f633836f6f4faffd63999667254e85fb3d84e5d68e2ec7dae832070056298123881b2b5dfeaa2f21a38538e5734bdfadbd467c3154f304b018d316efab16

test:
  secret_key_base: 22e1033207d5b557efa9d71832d9ffff292313d69a9e28de6ca940bfb1e9993adfce14eb1203e51f5bd759ee446786b98ee951d144cb3a3ac0c1a977d6f76a39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
